### ISSUE TITLE
问题：在使用weak_ptr解决循环引用的例子中，有两行代码是不是写反了

### ISSUE THREAD

**Issue by gaoxinge** [parallel101/course#1]
@archibate 

下面两行代码是不是写反了：

https://github.com/parallel101/course/blob/3940bba4ab8686348b52cf0bb064548d70ee22e0/02/24/3.cpp#L13-L14

是不是应该先获取裸指针，再使用`std::move`移交拥有权，如下：

```cpp
 child->m_parent = parent.get(); 
 parent->m_child = std::move(child);  // 移交 child 的所属权给 parent 
```

**Comment by archibate** [comment]
说的对！感谢提醒。
