### ISSUE TITLE
std::string  使用迭代器，删除\r的时候，没办法删除干净

### ISSUE THREAD

**Issue by qd1308504206** [parallel101/course#12]
```	
	std::string src = "\r\nabc\r\r\r\r\r\r\r\r123456\nABCDEF\r\n\r\n\r\r\r\r";
	std::remove_if(src.begin(), src.end(), [](char c) {
		return c == '\r';
	});

	auto size = src.size();


	//我认为应该是 \nabc123456\nABCDEF\n\n
	//实际却是：src = "\nabc123456\nABCDEF\n\n\nABCDEF\r\n\r\n\r\r\r\r"
```

最近在学习彭老师的课程，学到了 string其实也有迭代器。然后就找了一个remove_if函数试了一下。

请彭老师帮忙解答一下。这是为什么呢？

我的电脑是win10 64位， 使用的是virtual stdio 2022 preview

![image](https://user-images.githubusercontent.com/25291683/179895866-347d833e-6aac-4364-9993-dba7e1306b52.png)

**Comment by qd1308504206** [comment]
必须写成这样子，才能成功。很是疑惑
![image](https://user-images.githubusercontent.com/25291683/179896368-ef3b040c-9364-4590-b182-152a02aaa126.png)

**Comment by archibate** [comment]
remove_if用法错误，正确写法是:
src.erase(remove_if(src.begin(), src.end(), functor), src.end());
或者用cpp20的std::erase_if:
erase_if(src, functor);












无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月20日(周三) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/course] std::string  使用迭代器，删除\r的时候，没办法删除干净 (Issue #12)




 
`std::string src = "\r\nabc\r\r\r\r\r\r\r\r123456\nABCDEF\r\n\r\n\r\r\r\r";
 std::remove_if(src.begin(), src.end(), [](const char&amp; c) {
 return c == '\r';
 });
 //我认为应该是 \nabc123456\nABCDEF\n\n //实际却是：src = "\nabc123456\nABCDEF\n\n\nABCDEF\r\n\r\n\r\r\r\r"  
`
 
最近在学习彭老师的课程，学到了 string其实也有迭代器。然后就找了一个remove_if函数试了一下。
 
请彭老师帮忙解答一下。这是为什么呢？
 
我的电脑是win10 64位， 使用的是virtual stdio 2022 preview

**Comment by archibate** [comment]
remove_if并不会缩短string的长度，他只会把没有删除的元素“移动”到靠头的位置，剩余的元素仍然存在，需要用erase或resize调整大小才能真正删除。











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月20日(周三) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/course] std::string  使用迭代器，删除\r的时候，没办法删除干净 (Issue #12)




 
`std::string src = "\r\nabc\r\r\r\r\r\r\r\r123456\nABCDEF\r\n\r\n\r\r\r\r";
 std::remove_if(src.begin(), src.end(), [](const char&amp; c) {
 return c == '\r';
 });
 //我认为应该是 \nabc123456\nABCDEF\n\n //实际却是：src = "\nabc123456\nABCDEF\n\n\nABCDEF\r\n\r\n\r\r\r\r"  
`
 
最近在学习彭老师的课程，学到了 string其实也有迭代器。然后就找了一个remove_if函数试了一下。
 
请彭老师帮忙解答一下。这是为什么呢？
 
我的电脑是win10 64位， 使用的是virtual stdio 2022 preview

**Comment by qd1308504206** [comment]
感谢大佬解答

看了教程https://en.cppreference.com/w/cpp/algorithm/remove 之后，才恍然大悟。
![image](https://user-images.githubusercontent.com/25291683/180149981-143cc21f-cb99-4b25-82a8-beeae84134c5.png)
