### ISSUE TITLE
error: missing template arguments before ‘grd’

### ISSUE THREAD

**Issue by kdurant** [parallel101/course#6]
https://github.com/parallel101/course/blob/fe22cd6d52c94d945f4fa924a9782074d3b73f5e/05/03_mutex/04/main.cpp#L12

**Comment by archibate** [comment]
you need c++17











无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: ***@***.***&gt;
Date: Wed, Jan 26, 2022 13:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [parallel101/course] error: missing template arguments before ‘grd’ (Issue #6)




 
Closed #6.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
